title: Progetto
options:
  navigation:
    status: listed
    template: all

columns:
  main:
    width: 2/3
    sections: 
      years:
        type: fields
        fields:
          years:
            label: Anni
            type: text
            width: 1/2
      info:
        type: fields
        fields:
          name:
            label: Titolo dell'evento
            type: text
            width: 2/3
          type:
            label: Tipologia di evento
            type: text
            width: 1/3
          location:
            label: Luogo
            type: text
            width: 1/2
      copy:
        type: fields
        fields:
          lefttext:
            label: Testo
            width: 1/2
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - email
            nodes: false
          righttext:
            label: false
            width: 1/2
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - email
            nodes: false
  sidebar:
    width: 1/3
    sections:
      media:
        type: fields
        fields:
          logo:
            type: files
            label: Loghi
            template: logo
            uploads: logo
            query: page.images.filterBy('template', 'logo')
          gallery:
            type: files
            label: Galleria immagini
            template: image
            uploads: image
            query: page.images.filterBy('template', 'image')
            info: false
            sortable: true
          video:
            type: files
            label: Video
            template: video
            uploads: video
            query: page.videos