title: Progetto
options:
  navigation:
    status: listed
    template: all

columns:
  info:
    width: 3/4
    sections:
      years:
        type: fields
        fields:
          years:
            label: Periodo di attività
            placeholder: Periodo di attività
            type: text
            width: 1/2
      info:
        type: fields
        fields:
          name:
            label: Nome del progetto
            placeholder: Nome del progetto
            type: text
            width: 1/2
          type:
            label: Tipologia di progetto
            placeholder: Tipologia di progetto
            type: text
            width: 1/2
          location:
            label: Informazioni extra
            placeholder: Informazioni extra
            type: text
            width: 1/2
  main:
    width: 3/4
    sections: 
      copy:
        type: fields
        fields:
          lefttext:
            label: Testo
            width: 1/2
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - email
            nodes: false
            placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sed viverra ipsum nunc aliquet. Ornare aenean euismod elementum nisi."
          righttext:
            label: false
            width: 1/2
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - email
            nodes: false
            placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sed viverra ipsum nunc aliquet. Ornare aenean euismod elementum nisi."
  sidebar:
    width: 1/4
    sections:
      media:
        type: fields
        fields:
          logo:
            type: files
            label: Loghi
            template: logo
            uploads: logo
            query: page.images.filterBy('template', 'logo')
          gallery:
            type: files
            label: Galleria immagini
            template: image
            uploads: image
            query: page.images.filterBy('template', 'image')
            info: false
            sortable: true
          video:
            type: files
            label: Video
            template: video
            uploads: video
            query: page.videos