title: MAGMA

columns:
  main:
    width: 2/3
    sections:
      pages:
        label: Pagine
        type: pages
        image: false
        templates:
          - home
  sidebar:
    width: 1/3
    sections:
      global:
        type: fields
        fields:
          instagram:
            label: Instagram
            type: text
          facebook:
            label: Facebook
            type: text
          email:
            label: Email
            type: text
          footer:
            label: Footer
            type: text